################## Reading Data ##################
Reading_Data_Location:
  secom_data_values_location: '/Users/carlosmonsivais/Desktop/secom/data/secom.data'
  secom_data_labels_location: '/Users/carlosmonsivais/Desktop/secom/data/secom_labels.data'


################## EDA Plot Storage ##################
EDA_Visualizatiion_Graph_Output: '/Users/carlosmonsivais/Desktop/secom/EDA_Output_Plots'


################## Data Cleaning Values ##################
Missing_Value_Threshold: 0.95
Unique_Value_Threshold: 3
Correlation_Drop_Threshold: 0.60


################## Random State ##################
Random_State_Value: 3


################## Output Data ##################
Output_Data_Location:
  merged_data_location: '/Users/carlosmonsivais/Desktop/secom/data/merged_original_data.csv'
  before_data_imputation_location: '/Users/carlosmonsivais/Desktop/secom/data/before_data_imputation.csv'
  clean_data_location: '/Users/carlosmonsivais/Desktop/secom/data/clean_data.csv'
  training_data_output_location: '/Users/carlosmonsivais/Desktop/secom/data/training_data.csv'
  testing_data_output_location: '/Users/carlosmonsivais/Desktop/secom/data/testing_data.csv'